export const navigation = [
  {
    title: 'Introduction',
    links: [
      { title: 'Why Directive', href: '/docs/why-directive' },
      { title: 'Philosophy', href: '/docs/philosophy' },
      { title: 'Quick Start', href: '/docs/quick-start' },
      { title: 'Installation', href: '/docs/installation' },
      { title: 'Core Concepts', href: '/docs/core-concepts' },
      { title: 'Glossary', href: '/docs/glossary' },
      { title: 'Comparison', href: '/docs/comparison' },
    ],
  },
  {
    title: 'Core API',
    links: [
      { title: 'Core API Overview', href: '/docs/core-api' },
      { title: 'Module & System', href: '/docs/module-system' },
      { title: 'Facts', href: '/docs/facts' },
      { title: 'Derivations', href: '/docs/derivations' },
      { title: 'Constraints', href: '/docs/constraints' },
      { title: 'Resolvers', href: '/docs/resolvers' },
      { title: 'Effects', href: '/docs/effects' },
      { title: 'Events', href: '/docs/events' },
      { title: 'Builders', href: '/docs/builders' },
    ],
  },
  {
    title: 'Schema & Types',
    links: [
      { title: 'Schema Overview', href: '/docs/schema-overview' },
      { title: 'Type Builders', href: '/docs/type-builders' },
      { title: 'Zod Integration', href: '/docs/zod-integration' },
      { title: 'Type Assertions', href: '/docs/type-assertions' },
    ],
  },
  {
    title: 'Framework Adapters',
    links: [
      { title: 'Adapter Overview', href: '/docs/adapters/overview' },
      { title: 'React', href: '/docs/adapters/react' },
      { title: 'Vue', href: '/docs/adapters/vue' },
      { title: 'Svelte', href: '/docs/adapters/svelte' },
      { title: 'Solid', href: '/docs/adapters/solid' },
      { title: 'Lit', href: '/docs/adapters/lit' },
    ],
  },
  {
    title: 'Works With',
    links: [
      { title: 'Overview', href: '/docs/works-with/overview' },
      { title: 'Redux', href: '/docs/works-with/redux' },
      { title: 'Zustand', href: '/docs/works-with/zustand' },
      { title: 'XState', href: '/docs/works-with/xstate' },
      { title: 'React Query', href: '/docs/works-with/react-query' },
      { title: 'Web Worker', href: '/docs/works-with/worker' },
    ],
  },
  {
    title: 'Plugins',
    links: [
      { title: 'Plugin Overview', href: '/docs/plugins/overview' },
      { title: 'Logging', href: '/docs/plugins/logging' },
      { title: 'DevTools', href: '/docs/plugins/devtools' },
      { title: 'Persistence', href: '/docs/plugins/persistence' },
      { title: 'Performance', href: '/docs/plugins/performance' },
      { title: 'Custom Plugins', href: '/docs/plugins/custom' },
    ],
  },
  {
    title: 'AI & Agents',
    links: [
      { title: 'AI Overview', href: '/docs/ai/overview' },
      { title: 'Orchestrator', href: '/docs/ai/orchestrator' },
      { title: 'Agent Stack', href: '/docs/ai/agent-stack' },
      { title: 'Streaming', href: '/docs/ai/streaming' },
      { title: 'Multi-Agent', href: '/docs/ai/multi-agent' },
      { title: 'MCP Integration', href: '/docs/ai/mcp' },
      { title: 'Guardrails', href: '/docs/ai/guardrails' },
      { title: 'Running Agents', href: '/docs/ai/running-agents' },
    ],
  },
  {
    title: 'Security & Compliance',
    links: [
      { title: 'Security Overview', href: '/docs/security/overview' },
      { title: 'PII Detection', href: '/docs/security/pii' },
      { title: 'Prompt Injection', href: '/docs/security/prompt-injection' },
      { title: 'Audit Trail', href: '/docs/security/audit' },
      { title: 'GDPR/CCPA', href: '/docs/security/compliance' },
    ],
  },
  {
    title: 'Advanced',
    links: [
      { title: 'Advanced Overview', href: '/docs/advanced/overview' },
      { title: 'Multi-Module', href: '/docs/advanced/multi-module' },
      { title: 'Time-Travel', href: '/docs/advanced/time-travel' },
      { title: 'Snapshots', href: '/docs/advanced/snapshots' },
      { title: 'SSR & Hydration', href: '/docs/advanced/ssr' },
      { title: 'Error Handling', href: '/docs/advanced/errors' },
    ],
  },
  {
    title: 'How-To Guides',
    links: [
      { title: 'Overview', href: '/docs/how-to/overview' },
      { title: 'Loading & Error States', href: '/docs/how-to/loading-states' },
      { title: 'Authentication Flow', href: '/docs/how-to/auth-flow' },
      { title: 'WebSocket Connections', href: '/docs/how-to/websockets' },
      { title: 'Optimistic Updates', href: '/docs/how-to/optimistic-updates' },
      { title: 'Organize Modules', href: '/docs/how-to/organize-modules' },
      { title: 'Optimize Re-Renders', href: '/docs/how-to/optimize-rerenders' },
      { title: 'Debounce Constraints', href: '/docs/how-to/debounce-constraints' },
      { title: 'Dynamic Modules', href: '/docs/how-to/dynamic-modules' },
      { title: 'Persist State', href: '/docs/how-to/persist-state' },
      { title: 'Batch Mutations', href: '/docs/how-to/batch-mutations' },
      { title: 'Test Async Chains', href: '/docs/how-to/test-async-chains' },
      { title: 'Debug with Time-Travel', href: '/docs/how-to/debug-time-travel' },
    ],
  },
  {
    title: 'Testing',
    links: [
      { title: 'Testing Overview', href: '/docs/testing/overview' },
      { title: 'Mock Resolvers', href: '/docs/testing/mock-resolvers' },
      { title: 'Fake Timers', href: '/docs/testing/fake-timers' },
      { title: 'Assertions', href: '/docs/testing/assertions' },
    ],
  },
  {
    title: 'Migration',
    links: [
      { title: 'Migration Overview', href: '/docs/migration/overview' },
      { title: 'From Redux', href: '/docs/migration/from-redux' },
      { title: 'From Zustand', href: '/docs/migration/from-zustand' },
      { title: 'From XState', href: '/docs/migration/from-xstate' },
    ],
  },
  {
    title: 'Examples',
    links: [
      { title: 'Examples Overview', href: '/docs/examples/overview' },
      { title: 'Counter', href: '/docs/examples/counter' },
      { title: 'Data Fetching', href: '/docs/examples/data-fetching' },
      { title: 'Form Validation', href: '/docs/examples/form-validation' },
      { title: 'Multi-Module App', href: '/docs/examples/multi-module' },
      { title: 'AI Agent', href: '/docs/examples/ai-agent' },
    ],
  },
  {
    title: 'API Reference',
    links: [
      { title: 'API Overview', href: '/docs/api/overview' },
      { title: 'Core API', href: '/docs/api/core' },
      { title: 'Types', href: '/docs/api/types' },
      { title: 'React Hooks', href: '/docs/api/react' },
      { title: 'Vue Composables', href: '/docs/api/vue' },
      { title: 'Svelte Hooks', href: '/docs/api/svelte' },
      { title: 'Solid Hooks', href: '/docs/api/solid' },
      { title: 'Lit Controllers', href: '/docs/api/lit' },
    ],
  },
  {
    title: 'Community',
    links: [
      { title: 'Theme Vote', href: '/docs/community/theme-vote' },
    ],
  },
  {
    title: 'Help',
    links: [
      { title: 'FAQ', href: '/docs/faq' },
      { title: 'Troubleshooting', href: '/docs/troubleshooting' },
      { title: 'Brand Guide', href: '/docs/branding' },
    ],
  },
]
