import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		react: "src/adapters/frameworks/react.tsx",
		vue: "src/adapters/frameworks/vue.ts",
		svelte: "src/adapters/frameworks/svelte.ts",
		solid: "src/adapters/frameworks/solid.ts",
		lit: "src/adapters/frameworks/lit.ts",
		zustand: "src/adapters/bridges/zustand.ts",
		"react-query": "src/adapters/bridges/react-query.ts",
		xstate: "src/adapters/bridges/xstate.ts",
		redux: "src/adapters/bridges/redux.ts",
		ai: "src/adapters/ai/index.ts",
		"openai-agents": "src/adapters/ai/index.ts",
		worker: "src/adapters/bridges/worker.ts",
		"plugins/index": "src/plugins/index.ts",
		testing: "src/utils/testing.ts",
		templates: "src/utils/templates.ts",
	},
	format: ["esm", "cjs"],
	dts: true,
	sourcemap: true,
	clean: true,
	splitting: false,
	treeshake: true,
	target: "es2022",
	external: [
		"react",
		"react-dom",
		"vue",
		"svelte",
		"solid-js",
		"lit",
		"zustand",
		"@tanstack/react-query",
		"xstate",
		"@reduxjs/toolkit",
		"redux",
		"@openai/agents",
	],
});
