// Bake every @directive-run/<x> package's metadata into a typed
// module at src/generated/package-registry.ts so the MCP server's
// list_packages and get_package_info tools can answer without either
// (a) walking packages/<x>/package.json at runtime (the published
// tarball does not contain them) or (b) hitting npm on every call
// (network cost + rate limits).
//
// Live-version reconciliation happens at tool-call time in
// packages/mcp/src/packages.ts — this script bakes only the STATIC
// fields. Field allowlist mirrors AE security review #6 — never bake
// absolute paths, file: dependencies, or scripts.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const WORKSPACE_ROOT = resolve(PKG_ROOT, "..", "..");
const PACKAGES_DIR = join(WORKSPACE_ROOT, "packages");
const OUT_FILE = join(PKG_ROOT, "src", "generated", "package-registry.ts");

interface SourceManifest {
  name?: string;
  version?: string;
  description?: string;
  homepage?: string;
  repository?: { directory?: string } | string;
  keywords?: string[];
  private?: boolean;
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
  exports?: Record<string, unknown>;
}

interface BakedEntry {
  name: string;
  version: string;
  description: string;
  homepage?: string;
  keywords: string[];
  dependencies: string[];
  peerDependencies: string[];
  optionalDependencies: string[];
  exports: string[];
  directory: string;
  /** True when published to npm; false for private workspace packages. */
  published: boolean;
}

function assertNoAbsolutePathDeps(
  pkgName: string,
  deps: Record<string, string> | undefined,
): void {
  if (!deps) {
    return;
  }
  for (const [name, range] of Object.entries(deps)) {
    if (range.startsWith("file:") || range.startsWith("/")) {
      throw new Error(
        `package-registry build: ${pkgName} declares ${name} with non-portable range "${range}". Bake refused.`,
      );
    }
  }
}

function shouldInclude(pkgName: string): boolean {
  // We keep private packages in the registry (the agent might still
  // want to know about them) but mark them with `published: false`
  // so `get_package_info` doesn't hand out misleading npm URLs.
  return pkgName.startsWith("@directive-run/");
}

function depKeys(deps?: Record<string, string>): string[] {
  if (!deps) {
    return [];
  }
  return Object.keys(deps).sort();
}

function exportKeys(exports?: Record<string, unknown>): string[] {
  if (!exports) {
    return [];
  }
  return Object.keys(exports).sort();
}

function bakeOne(dir: string): BakedEntry | null {
  const manifestPath = join(PACKAGES_DIR, dir, "package.json");
  let raw: string;
  try {
    raw = readFileSync(manifestPath, "utf-8");
  } catch {
    return null;
  }
  const manifest = JSON.parse(raw) as SourceManifest;
  if (!manifest.name) {
    return null;
  }
  if (!shouldInclude(manifest.name)) {
    return null;
  }

  assertNoAbsolutePathDeps(manifest.name, manifest.dependencies);
  assertNoAbsolutePathDeps(manifest.name, manifest.peerDependencies);
  assertNoAbsolutePathDeps(manifest.name, manifest.optionalDependencies);

  return {
    name: manifest.name,
    version: manifest.version ?? "0.0.0",
    description: manifest.description ?? "",
    homepage: manifest.homepage,
    keywords: manifest.keywords ?? [],
    dependencies: depKeys(manifest.dependencies),
    peerDependencies: depKeys(manifest.peerDependencies),
    optionalDependencies: depKeys(manifest.optionalDependencies),
    exports: exportKeys(manifest.exports),
    directory: dir,
    published: !manifest.private,
  };
}

function bakeAll(): BakedEntry[] {
  const entries: BakedEntry[] = [];
  for (const dir of readdirSync(PACKAGES_DIR).sort()) {
    const entry = bakeOne(dir);
    if (entry) {
      entries.push(entry);
    }
  }
  return entries;
}

function render(entries: BakedEntry[]): string {
  const banner = [
    "// AUTO-GENERATED by packages/mcp/scripts/build-package-registry.ts",
    "// Do not edit by hand. Run `pnpm --filter @directive-run/mcp build:registry`.",
    "",
  ].join("\n");

  return `${banner}export interface PackageRegistryEntry {
  name: string;
  version: string;
  description: string;
  homepage?: string;
  keywords: readonly string[];
  dependencies: readonly string[];
  peerDependencies: readonly string[];
  optionalDependencies: readonly string[];
  exports: readonly string[];
  directory: string;
  published: boolean;
}

export const PACKAGE_REGISTRY: readonly PackageRegistryEntry[] = ${JSON.stringify(
    entries,
    null,
    2,
  )} as const;

export const PACKAGE_REGISTRY_BUILT_AT = ${JSON.stringify(
    new Date().toISOString(),
  )};
`;
}

const entries = bakeAll();
if (entries.length === 0) {
  console.error("package-registry build: no @directive-run/* packages found");
  process.exit(1);
}
writeFileSync(OUT_FILE, render(entries), "utf-8");
console.log(
  `package-registry build: wrote ${entries.length} entries → ${OUT_FILE.replace(WORKSPACE_ROOT, ".")}`,
);
