'use client'

import { memo, useCallback, useEffect, useState } from 'react'
import clsx from 'clsx'

interface StepInfo {
  title: string
  description: string
  example: string
}

const STEPS: Record<string, StepInfo> = {
  facts: {
    title: 'Facts',
    description: 'Observable state that triggers the constraint system when changed.',
    example: 'system.facts.userId = 123',
  },
  constraints: {
    title: 'Constraints',
    description: 'Rules that declare what must be true. When the condition is met, a requirement is generated.',
    example: 'when: (f) => f.userId > 0 && !f.user',
  },
  requirements: {
    title: 'Requirements',
    description: 'Typed objects describing what the system needs. Generated by constraints, fulfilled by resolvers.',
    example: '{ type: "FETCH_USER", payload: { id: 123 } }',
  },
  resolvers: {
    title: 'Resolvers',
    description: 'Async functions that fulfill requirements and update facts, completing the loop.',
    example: 'ctx.facts.user = await api.getUser(...)',
  },
}

const ANIMATION_STEPS = ['facts', 'arrow1', 'constraints', 'arrow2', 'requirements', 'arrow3', 'resolvers', 'return']

function Tooltip({ step, position }: { step: string; position: { x: number; y: number } }) {
  const info = STEPS[step]
  if (!info) return null

  return (
    <div
      className="pointer-events-none absolute z-50 w-72 rounded-lg bg-slate-900 p-4 text-sm text-white shadow-xl dark:bg-slate-700"
      style={{
        left: `${position.x}px`,
        top: `${position.y - 120}px`,
        transform: 'translateX(-50%)',
      }}
    >
      <div className="font-semibold" style={{ color: 'var(--brand-primary-400)' }}>{info.title}</div>
      <div className="mt-1 text-slate-300">{info.description}</div>
      <code className="mt-2 block rounded bg-slate-800 px-2 py-1 text-xs text-emerald-400 dark:bg-slate-600">
        {info.example}
      </code>
      <div className="absolute -bottom-2 left-1/2 -translate-x-1/2 border-8 border-transparent border-t-slate-900 dark:border-t-slate-700" />
    </div>
  )
}

export const ConstraintFlowDiagram = memo(function ConstraintFlowDiagram() {
  const [isAnimating, setIsAnimating] = useState(false)
  const [currentStep, setCurrentStep] = useState(-1)
  const [hoveredStep, setHoveredStep] = useState<string | null>(null)
  const [tooltipPosition, setTooltipPosition] = useState({ x: 0, y: 0 })

  // Auto-start animation on mount
  useEffect(() => {
    const timer = setTimeout(() => {
      setIsAnimating(true)
    }, 500)
    return () => clearTimeout(timer)
  }, [])

  // Animation loop
  useEffect(() => {
    if (!isAnimating) {
      setCurrentStep(-1)
      return
    }

    const interval = setInterval(() => {
      setCurrentStep((prev) => (prev + 1) % ANIMATION_STEPS.length)
    }, 800)

    return () => clearInterval(interval)
  }, [isAnimating])

  const handleMouseEnter = useCallback((step: string, event: React.MouseEvent) => {
    const rect = event.currentTarget.getBoundingClientRect()
    const parentRect = event.currentTarget.closest('.constraint-diagram')?.getBoundingClientRect()
    if (parentRect) {
      setTooltipPosition({
        x: rect.left - parentRect.left + rect.width / 2,
        y: rect.top - parentRect.top,
      })
    }
    setHoveredStep(step)
    setIsAnimating(false)
  }, [])

  const handleMouseLeave = useCallback(() => {
    setHoveredStep(null)
    setIsAnimating(true)
  }, [])

  const getStepClass = (step: string) => {
    const stepIndex = ANIMATION_STEPS.indexOf(step)
    const isActive = currentStep === stepIndex || hoveredStep === step
    return isActive
  }

  const getArrowClass = (arrow: string) => {
    const stepIndex = ANIMATION_STEPS.indexOf(arrow)
    return currentStep === stepIndex
  }

  return (
    <div className="constraint-diagram not-prose relative my-8 overflow-visible">
      {/* Controls */}
      <div className="mb-4 flex items-center justify-center gap-4">
        <button
          onClick={() => setIsAnimating(!isAnimating)}
          className={clsx(
            'flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium transition',
            isAnimating
              ? 'bg-brand-primary text-white hover:bg-brand-primary-600'
              : 'bg-slate-200 text-slate-700 hover:bg-slate-300 dark:bg-slate-700 dark:text-slate-300 dark:hover:bg-slate-600'
          )}
        >
          {isAnimating ? (
            <>
              <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM7 8a1 1 0 012 0v4a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v4a1 1 0 102 0V8a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              Pause
            </>
          ) : (
            <>
              <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clipRule="evenodd" />
              </svg>
              Play
            </>
          )}
        </button>
        <span className="text-xs text-slate-500 dark:text-slate-400">
          Hover over any box to learn more
        </span>
      </div>

      {/* Tooltip */}
      {hoveredStep && STEPS[hoveredStep] && (
        <Tooltip step={hoveredStep} position={tooltipPosition} />
      )}

      {/* Diagram */}
      <div className="overflow-x-auto">
        <svg
          viewBox="0 0 800 200"
          className="mx-auto h-auto w-full max-w-3xl"
          aria-labelledby="constraint-flow-title"
          role="img"
        >
          <title id="constraint-flow-title">Directive Constraint Flow Diagram - Interactive</title>

          {/* Animated gradient for data flow */}
          <defs>
            <linearGradient id="flowGradient" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="var(--brand-primary)" stopOpacity="0">
                <animate attributeName="offset" values="-0.5;1" dur="1.5s" repeatCount="indefinite" />
              </stop>
              <stop offset="50%" stopColor="var(--brand-primary)" stopOpacity="1">
                <animate attributeName="offset" values="0;1.5" dur="1.5s" repeatCount="indefinite" />
              </stop>
              <stop offset="100%" stopColor="var(--brand-primary)" stopOpacity="0">
                <animate attributeName="offset" values="0.5;2" dur="1.5s" repeatCount="indefinite" />
              </stop>
            </linearGradient>

            <marker
              id="arrowhead"
              markerWidth="10"
              markerHeight="7"
              refX="9"
              refY="3.5"
              orient="auto"
            >
              <polygon
                points="0 0, 10 3.5, 0 7"
                className="fill-slate-400 dark:fill-slate-500"
              />
            </marker>

            <marker
              id="arrowhead-active"
              markerWidth="10"
              markerHeight="7"
              refX="9"
              refY="3.5"
              orient="auto"
            >
              <polygon
                points="0 0, 10 3.5, 0 7"
                className="fill-brand-primary"
              />
            </marker>
          </defs>

          {/* Facts Box */}
          <g
            transform="translate(20, 70)"
            className="cursor-pointer"
            onMouseEnter={(e) => handleMouseEnter('facts', e)}
            onMouseLeave={handleMouseLeave}
          >
            <rect
              width="120"
              height="60"
              rx="8"
              className={clsx(
                'transition-all duration-300',
                getStepClass('facts')
                  ? 'fill-brand-primary-200 stroke-brand-primary-600 dark:fill-brand-primary-800 dark:stroke-brand-primary-300'
                  : 'fill-brand-primary-100 stroke-brand-primary dark:fill-brand-primary-900/50 dark:stroke-brand-primary-400'
              )}
              strokeWidth={getStepClass('facts') ? 3 : 2}
            />
            {getStepClass('facts') && (
              <rect
                width="120"
                height="60"
                rx="8"
                fill="none"
                stroke="var(--brand-primary)"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate attributeName="opacity" values="0.5;0;0.5" dur="1s" repeatCount="indefinite" />
              </rect>
            )}
            <text
              x="60"
              y="35"
              textAnchor="middle"
              className="pointer-events-none fill-brand-primary-700 text-sm font-semibold dark:fill-brand-primary-300"
            >
              Facts
            </text>
            <text
              x="60"
              y="50"
              textAnchor="middle"
              className="pointer-events-none fill-brand-primary-600 text-xs dark:fill-brand-primary-400"
            >
              (state)
            </text>
          </g>

          {/* Arrow 1 */}
          <g transform="translate(150, 100)">
            <line
              x1="0"
              y1="0"
              x2="60"
              y2="0"
              className={clsx(
                'transition-all duration-300',
                getArrowClass('arrow1') ? 'stroke-brand-primary' : 'stroke-slate-400 dark:stroke-slate-500'
              )}
              strokeWidth={getArrowClass('arrow1') ? 3 : 2}
              markerEnd={getArrowClass('arrow1') ? 'url(#arrowhead-active)' : 'url(#arrowhead)'}
            />
            {getArrowClass('arrow1') && (
              <circle r="4" fill="var(--brand-primary)">
                <animate attributeName="cx" values="0;60" dur="0.5s" fill="freeze" />
              </circle>
            )}
            <text
              x="30"
              y="-8"
              textAnchor="middle"
              className="fill-slate-500 text-xs dark:fill-slate-400"
            >
              change
            </text>
          </g>

          {/* Constraints Box */}
          <g
            transform="translate(220, 70)"
            className="cursor-pointer"
            onMouseEnter={(e) => handleMouseEnter('constraints', e)}
            onMouseLeave={handleMouseLeave}
          >
            <rect
              width="140"
              height="60"
              rx="8"
              className={clsx(
                'transition-all duration-300',
                getStepClass('constraints')
                  ? 'fill-amber-200 stroke-amber-600 dark:fill-amber-800 dark:stroke-amber-300'
                  : 'fill-amber-100 stroke-amber-500 dark:fill-amber-900/50 dark:stroke-amber-400'
              )}
              strokeWidth={getStepClass('constraints') ? 3 : 2}
            />
            {getStepClass('constraints') && (
              <rect
                width="140"
                height="60"
                rx="8"
                fill="none"
                stroke="#f59e0b"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate attributeName="opacity" values="0.5;0;0.5" dur="1s" repeatCount="indefinite" />
              </rect>
            )}
            <text
              x="70"
              y="35"
              textAnchor="middle"
              className="pointer-events-none fill-amber-700 text-sm font-semibold dark:fill-amber-300"
            >
              Constraints
            </text>
            <text
              x="70"
              y="50"
              textAnchor="middle"
              className="pointer-events-none fill-amber-600 text-xs dark:fill-amber-400"
            >
              (when condition)
            </text>
          </g>

          {/* Arrow 2 */}
          <g transform="translate(370, 100)">
            <line
              x1="0"
              y1="0"
              x2="60"
              y2="0"
              className={clsx(
                'transition-all duration-300',
                getArrowClass('arrow2') ? 'stroke-brand-primary' : 'stroke-slate-400 dark:stroke-slate-500'
              )}
              strokeWidth={getArrowClass('arrow2') ? 3 : 2}
              markerEnd={getArrowClass('arrow2') ? 'url(#arrowhead-active)' : 'url(#arrowhead)'}
            />
            {getArrowClass('arrow2') && (
              <circle r="4" fill="var(--brand-primary)">
                <animate attributeName="cx" values="0;60" dur="0.5s" fill="freeze" />
              </circle>
            )}
            <text
              x="30"
              y="-8"
              textAnchor="middle"
              className="fill-slate-500 text-xs dark:fill-slate-400"
            >
              require
            </text>
          </g>

          {/* Requirements Box */}
          <g
            transform="translate(440, 70)"
            className="cursor-pointer"
            onMouseEnter={(e) => handleMouseEnter('requirements', e)}
            onMouseLeave={handleMouseLeave}
          >
            <rect
              width="140"
              height="60"
              rx="8"
              className={clsx(
                'transition-all duration-300',
                getStepClass('requirements')
                  ? 'fill-violet-200 stroke-violet-600 dark:fill-violet-800 dark:stroke-violet-300'
                  : 'fill-violet-100 stroke-violet-500 dark:fill-violet-900/50 dark:stroke-violet-400'
              )}
              strokeWidth={getStepClass('requirements') ? 3 : 2}
            />
            {getStepClass('requirements') && (
              <rect
                width="140"
                height="60"
                rx="8"
                fill="none"
                stroke="#8b5cf6"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate attributeName="opacity" values="0.5;0;0.5" dur="1s" repeatCount="indefinite" />
              </rect>
            )}
            <text
              x="70"
              y="35"
              textAnchor="middle"
              className="pointer-events-none fill-violet-700 text-sm font-semibold dark:fill-violet-300"
            >
              Requirements
            </text>
            <text
              x="70"
              y="50"
              textAnchor="middle"
              className="pointer-events-none fill-violet-600 text-xs dark:fill-violet-400"
            >
              (what to do)
            </text>
          </g>

          {/* Arrow 3 */}
          <g transform="translate(590, 100)">
            <line
              x1="0"
              y1="0"
              x2="60"
              y2="0"
              className={clsx(
                'transition-all duration-300',
                getArrowClass('arrow3') ? 'stroke-brand-primary' : 'stroke-slate-400 dark:stroke-slate-500'
              )}
              strokeWidth={getArrowClass('arrow3') ? 3 : 2}
              markerEnd={getArrowClass('arrow3') ? 'url(#arrowhead-active)' : 'url(#arrowhead)'}
            />
            {getArrowClass('arrow3') && (
              <circle r="4" fill="var(--brand-primary)">
                <animate attributeName="cx" values="0;60" dur="0.5s" fill="freeze" />
              </circle>
            )}
            <text
              x="30"
              y="-8"
              textAnchor="middle"
              className="fill-slate-500 text-xs dark:fill-slate-400"
            >
              resolve
            </text>
          </g>

          {/* Resolvers Box */}
          <g
            transform="translate(660, 70)"
            className="cursor-pointer"
            onMouseEnter={(e) => handleMouseEnter('resolvers', e)}
            onMouseLeave={handleMouseLeave}
          >
            <rect
              width="120"
              height="60"
              rx="8"
              className={clsx(
                'transition-all duration-300',
                getStepClass('resolvers')
                  ? 'fill-emerald-200 stroke-emerald-600 dark:fill-emerald-800 dark:stroke-emerald-300'
                  : 'fill-emerald-100 stroke-emerald-500 dark:fill-emerald-900/50 dark:stroke-emerald-400'
              )}
              strokeWidth={getStepClass('resolvers') ? 3 : 2}
            />
            {getStepClass('resolvers') && (
              <rect
                width="120"
                height="60"
                rx="8"
                fill="none"
                stroke="#10b981"
                strokeWidth="2"
                opacity="0.5"
              >
                <animate attributeName="opacity" values="0.5;0;0.5" dur="1s" repeatCount="indefinite" />
              </rect>
            )}
            <text
              x="60"
              y="35"
              textAnchor="middle"
              className="pointer-events-none fill-emerald-700 text-sm font-semibold dark:fill-emerald-300"
            >
              Resolvers
            </text>
            <text
              x="60"
              y="50"
              textAnchor="middle"
              className="pointer-events-none fill-emerald-600 text-xs dark:fill-emerald-400"
            >
              (how to do it)
            </text>
          </g>

          {/* Return Arrow (curved) */}
          <path
            d="M 720 145 Q 720 175, 400 175 Q 80 175, 80 145"
            fill="none"
            className={clsx(
              'transition-all duration-300',
              getArrowClass('return') ? 'stroke-brand-primary' : 'stroke-slate-400 dark:stroke-slate-500'
            )}
            strokeWidth={getArrowClass('return') ? 3 : 2}
            strokeDasharray={getArrowClass('return') ? 'none' : '4 4'}
            markerEnd={getArrowClass('return') ? 'url(#arrowhead-active)' : 'url(#arrowhead)'}
          />
          <text
            x="400"
            y="190"
            textAnchor="middle"
            className="fill-slate-500 text-xs dark:fill-slate-400"
          >
            update facts (loop until settled)
          </text>
        </svg>
      </div>

      {/* Step indicator */}
      <div className="mt-4 flex justify-center gap-2">
        {['Facts', 'Constraints', 'Requirements', 'Resolvers'].map((label, i) => (
          <div
            key={label}
            className={clsx(
              'flex items-center gap-1 rounded-full px-2 py-1 text-xs transition-all',
              [0, 2, 4, 6].includes(currentStep) && Math.floor(currentStep / 2) === i
                ? 'bg-brand-primary-100 text-brand-primary-700 dark:bg-brand-primary-900 dark:text-brand-primary-300'
                : 'text-slate-400 dark:text-slate-500'
            )}
          >
            <span
              className={clsx(
                'h-2 w-2 rounded-full transition-all',
                [0, 2, 4, 6].includes(currentStep) && Math.floor(currentStep / 2) === i
                  ? 'bg-brand-primary'
                  : 'bg-slate-300 dark:bg-slate-600'
              )}
            />
            {label}
          </div>
        ))}
      </div>
    </div>
  )
})
