'use client'

import { memo, useMemo, useCallback } from 'react'
import type { Node, Edge } from '@xyflow/react'
import {
  DiagramWrapper,
  AnimationController,
  useAnimationLoop,
  diagramNodeTypes,
  diagramEdgeTypes,
  type StepNodeData,
} from './diagrams'

const STEPS = [
  { id: 'facts', label: 'Facts', subtitle: '(state)', colorScheme: 'primary' as const, tooltip: { description: 'Observable state that triggers the constraint system when changed.', example: 'system.facts.userId = 123' } },
  { id: 'constraints', label: 'Constraints', subtitle: '(when condition)', colorScheme: 'amber' as const, tooltip: { description: 'Rules that declare what must be true. When the condition is met, a requirement is generated.', example: 'when: (f) => f.userId > 0 && !f.user' } },
  { id: 'requirements', label: 'Requirements', subtitle: '(what to do)', colorScheme: 'violet' as const, tooltip: { description: 'Typed objects describing what the system needs. Generated by constraints, fulfilled by resolvers.', example: '{ type: "FETCH_USER", payload: { id: 123 } }' } },
  { id: 'resolvers', label: 'Resolvers', subtitle: '(how to do it)', colorScheme: 'emerald' as const, tooltip: { description: 'Async functions that fulfill requirements and update facts, completing the loop.', example: 'ctx.facts.user = await api.getUser(...)' } },
] as const

const ANIMATION_STEPS = ['facts', 'arrow1', 'constraints', 'arrow2', 'requirements', 'arrow3', 'resolvers', 'return'] as const

export const ConstraintFlowDiagram = memo(function ConstraintFlowDiagram() {
  const { phase, isPlaying, toggle, pause, play } = useAnimationLoop({
    totalPhases: ANIMATION_STEPS.length,
    interval: 800,
  })

  const currentStepName = phase >= 0 ? ANIMATION_STEPS[phase] : null

  const isStepActive = useCallback(
    (stepId: string) => currentStepName === stepId,
    [currentStepName],
  )

  const isArrowActive = useCallback(
    (arrowId: string) => currentStepName === arrowId,
    [currentStepName],
  )

  const nodes = useMemo<Node[]>(() => {
    const spacing = 220
    const y = 50

    return STEPS.map((step, i) => ({
      id: step.id,
      type: 'step',
      position: { x: 30 + i * spacing, y },
      data: {
        label: step.label,
        subtitle: step.subtitle,
        tooltip: step.tooltip,
        status: isStepActive(step.id) ? 'active' : 'idle',
        colorScheme: step.colorScheme,
      } satisfies StepNodeData,
    }))
  }, [isStepActive])

  const edges = useMemo<Edge[]>(() => [
    {
      id: 'facts->constraints',
      source: 'facts',
      target: 'constraints',
      type: 'labeled',
      data: { label: 'change', active: isArrowActive('arrow1') },
    },
    {
      id: 'constraints->requirements',
      source: 'constraints',
      target: 'requirements',
      type: 'labeled',
      data: { label: 'require', active: isArrowActive('arrow2') },
    },
    {
      id: 'requirements->resolvers',
      source: 'requirements',
      target: 'resolvers',
      type: 'labeled',
      data: { label: 'resolve', active: isArrowActive('arrow3') },
    },
    {
      id: 'resolvers->facts',
      source: 'resolvers',
      sourceHandle: 'bottom',
      target: 'facts',
      targetHandle: 'bottom',
      type: 'feedback',
      data: {
        label: 'update facts (loop until settled)',
        active: isArrowActive('return'),
        direction: 'below',
      },
    },
  ], [isArrowActive])

  const handleNodeMouseEnter = useCallback(
    (_event: React.MouseEvent, _node: Node) => {
      pause()
    },
    [pause],
  )

  const handleNodeMouseLeave = useCallback(() => {
    play()
  }, [play])

  return (
    <div className="constraint-diagram">
      <AnimationController
        isPlaying={isPlaying}
        onToggle={toggle}
        hint="Hover over any box to learn more"
      />

      <DiagramWrapper
        height={200}
        nodes={nodes}
        edges={edges}
        nodeTypes={diagramNodeTypes}
        edgeTypes={diagramEdgeTypes}
        onNodeMouseEnter={handleNodeMouseEnter}
        onNodeMouseLeave={handleNodeMouseLeave}
      />

      {/* Step indicator */}
      <div className="mt-4 flex justify-center gap-2">
        {STEPS.map((step, i) => {
          const stepActive = phase >= 0 && ANIMATION_STEPS[phase] === step.id

          return (
            <div
              key={step.id}
              className={`flex items-center gap-1 rounded-full px-2 py-1 text-xs transition-all ${
                stepActive
                  ? 'bg-sky-100 text-sky-700 dark:bg-sky-900 dark:text-sky-300'
                  : 'text-slate-400 dark:text-slate-500'
              }`}
            >
              <span
                className={`h-2 w-2 rounded-full transition-all ${
                  stepActive ? 'bg-sky-500' : 'bg-slate-300 dark:bg-slate-600'
                }`}
              />
              {step.label}
            </div>
          )
        })}
      </div>
    </div>
  )
})
